# Generated by Django 3.0.8 on 2020-08-02 06:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('fullname', models.CharField(max_length=15)),
                ('plantname', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('plantprice', models.FloatField(default=0)),
                ('plantimage', models.ImageField(default='default.jpeg', upload_to='plants')),
            ],
        ),
    ]
