# Generated by Django 3.0.8 on 2020-08-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200802_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='plantimage',
            field=models.ImageField(upload_to='plants'),
        ),
    ]
